// <auto-generated />
namespace EF6WhatsNew.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-rc1-20726")]
    public sealed partial class TweakSP : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TweakSP));
        
        string IMigrationMetadata.Id
        {
            get { return "201309042249090_TweakSP"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
